# Generated by Django 6.0.3 on 2026-04-01 06:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_title', models.CharField(blank=True, max_length=500)),
                ('context', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('arxiv_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=100)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['paper', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('abstract', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('arxiv_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_summary', models.TextField(blank=True)),
                ('main_contribution', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('key_results', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('future_work', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
