# Generated by Django 6.0.3 on 2026-04-01 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper'),
        ),
        migrations.AddField(
            model_name='citation',
            name='cited_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='papers.paper'),
        ),
        migrations.AddField(
            model_name='citation',
            name='citing_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='papers.paper'),
        ),
        migrations.AddField(
            model_name='papersummary',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='papers.paper'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('paper', 'chunk_index')},
        ),
    ]
